"""pharos docs — generate the agent-facing entry files from live data.

Writes into `<library_root>/<agent_files>/`:
    AGENT_START_HERE.md  the read-first orientation for any coding agent
    AGENT_API.md         the HTTP API reference

Every count in these files is queried from the live registry at generation
time (the 2026-09-17 audit found 17+ hand-maintained counts drifting in
two days -- numbers are generated, never typed). Re-run after importing
new content: `python pharos.py docs`.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

from . import config


def _counts(db_path: str) -> dict:
    conn = sqlite3.connect(db_path)
    out: dict = {}
    def one(key, sql):
        try:
            out[key] = conn.execute(sql).fetchone()[0]
        except sqlite3.OperationalError:
            out[key] = 0
    one("meshes", "SELECT COUNT(*) FROM meshes")
    one("mesh_packs", "SELECT COUNT(DISTINCT pack) FROM meshes")
    one("textures", "SELECT COUNT(*) FROM textures")
    one("audio", "SELECT COUNT(*) FROM audio")
    one("collection", "SELECT COUNT(*) FROM collection")
    one("local", "SELECT COUNT(*) FROM collection WHERE availability='local'")
    one("clips", "SELECT COUNT(*) FROM asset_files f JOIN assets a "
                 "ON a.id=f.asset_id WHERE a.id LIKE 'pack::Animation/%' "
                 "AND (lower(f.relative_path) LIKE '%.fbx' "
                 "OR lower(f.relative_path) LIKE '%.bvh')")
    conn.close()
    try:
        out["previews"] = len(list(config.PREVIEW_DIR.glob("*.webm"))) \
            if config.PREVIEW_DIR.is_dir() else 0
    except OSError:
        out["previews"] = 0
    return out


START_TEMPLATE = """# READ THIS FIRST — Agent Entry Point for {library_root}

You are looking at a personal 3D / texture / audio / animation asset
library. This folder is the single entry point: read the files listed
here IN THIS ORDER and you can answer asset questions WITHOUT walking
the disk. Generated by Pharos {generated}; every count below was
measured against the live registry at that moment.

## Step 1 — probe the local API (fastest path, prefer it)

    GET http://127.0.0.1:8765/api/stats

If it answers, use the HTTP API for everything — full reference in
`AGENT_API.md` (same folder). If it does not answer, the server is
simply not started; ask the human to run:

    python {repo}/pharos.py serve

## Step 2 — what is in this library (live counts)

| Section   | Count | Query with |
|---|---|---|
| Meshes    | {meshes} ({mesh_packs} packs) | `/api/meshes?q=door&min_dim=1.8&max_dim=2.4` |
| Textures  | {textures} PBR sets | `/api/textures/items?q=brick` |
| Audio     | {audio} sounds | `/api/audio/items?q=siren&min_dur=5` |
| Purchases | {collection} owned ({local} on disk) | `/api/collection/items?avail=local` |
| Animations| {clips} clips ({previews} previewed) | `/api/anim/clips?q=walk` |

Missing/zero sections mean the library genuinely has no such content
(or its import source is absent) — the system serves them as empty
results, never errors.

## Step 3 — the rules that matter

**Work in phases** (full manual: `<repo>/docs/AGENT_PLAYBOOK.md`):
Phase 1 = setup + crawl + INTERVIEW your user (are these all the
folders? crawl UE? purchase CSV?) until the server banner says
INGESTION COMPLETE and the user confirmed. Phase 2 = build, following
the priority lists:

1. Asset on disk → use it. 2. On demand (owned-not-downloaded) → ask
the user with a requisition list, never substitute silently. 3. Not in
the library → model it from scratch in the build and SAY SO in the
report. Textures: linked → use; fitting set exists → use; nothing →
generate procedurally and say so.

1. The library on disk is READ-ONLY for you. Locate and read files,
   never modify/move/delete them.
2. Prefer the API over disk walks — that is the entire point of this
   system (measured ~90% token savings vs filesystem crawling).
3. Dimension filters are METRES. `max_tri` is a triangle budget.
4. Availability: `local` = on disk now; `owned-not-downloaded` =
   purchasable — surface it as a requisition list, never substitute
   silently.
5. POST endpoints mutate human-visible state — only on explicit
   instruction (see AGENT_API.md §POST).
6. Blender needs NO plugin or MCP: builds run via
   `blender --background --factory-startup --python scene_builder.py`.
7. Scene building: query the API, author a scene manifest, validate,
   then build headless — the workflow is documented in the repo's
   `docs/CAPABILITIES.md` §5.

## Step 4 — fallback if the server is down

The per-section machine indexes beside this file (when present) let you
work offline: `library_index.json` / `*_library_files.jsonl` for audio
and textures, `models.jsonl` / `native_models.jsonl` for meshes,
`availability.jsonl` for ownership. Paths inside JSONL files are
RELATIVE — resolve against the section roots in `pharos_config.json`.

## Maintenance

- New content onboarding, config layout, and every capability: the
  repo's `docs/CAPABILITIES.md` (source of truth for what the system
  can and cannot do).
- Regenerate this file after imports: `python {repo}/pharos.py docs`.
"""

API_TEMPLATE = """# AGENT_API — Pharos HTTP API reference

Generated {generated}. Server: http://127.0.0.1:8765 (localhost, no
auth). All list endpoints paginate (`page`, `size` 8–500) and share the
search semantics in section D. File-serving routes are path-jailed to
the configured roots — outside paths return 404/403.

## A. Queries per section (GET)

| Endpoint | Key filters (all optional) | Result key |
|---|---|---|
| `/api/meshes` | `q`, `pack`, `source`, `theme`/`themes`, `min_dim`/`max_dim`, `min_h`/`max_h`, `max_tri`, `textures=1`, `sort=name|max_dim|triangles` | `items` |
| `/api/meshes/packs` | — (exact pack names + wiring health; call BEFORE `pack=`) | `packs` |
| `/api/meshes/themes` | — (theme vocabulary + counts) | `themes` |
| `/api/textures/items` | `q`, `group`, `sub` | `items` |
| `/api/textures/item?id=` | — | object (fields at top level + `item` copy) |
| `/api/audio/items` | `q`, `cat`, `sub`, `min_dur` (seconds) | `items` |
| `/api/audio/item?id=` | — | object (fields at top level + `item` copy) |
| `/api/collection/items` | `q`, `store`, `group`, `cat`, `avail=local|notdown` | `items` |
| `/api/collection/item?id=` | — | object (fields at top level + `item` copy) |
| `/api/anim/clips` | `q`, `packs` (pipe-separated), `page`, `size` | `clips` (NOT `items`) |
| `/api/anim/tree` | — | folders + counts |
| `/api/stats` | — | `stats` (legacy packs) + `sections` (live totals) |

(Windows PowerShell: `curl` is aliased to `Invoke-WebRequest` and the
`-s` flags hang — use `curl.exe`, or
`python -c "import urllib.request;print(urllib.request.urlopen('http://127.0.0.1:8765/api/stats').read()[:200])"`. HEAD requests work for link checks.)

## B. Mesh item fields (the ones that matter)

`fbx`/`fbx_path` absolute path · `bbox_m` [x,y,z] extents in metres ·
`max_dim_m`/`height_m` · `triangles` · `materials` (slot names) ·
`texture_count` · `themes` · `view_url` (3D preview) · `recipe` (per-slot
material wiring: `slots[].maps[]` with `role`/`file`/`channels`) ·
`hero_textures` (role → texture path; `{}` = unknown, NOT untextured) ·
`dim_suspect` (dims withheld as unreliable) · `tier`/`mode`/`exact`
(search-quality disclosure).

**Dimension provenance** (they are NOT all measured the same way):
`leartes` — exporter-reported per-mesh boxes (metres, trustworthy);
`kitbash3d` — Blender world-space AABB over the placed assembly (axis
order differs from the FBX file's own header); `scan` — file-level
extents from the raw FBX/OBJ (multi-object files report one box over
everything, no per-object transforms). Don't mix provenances in one
comparison.

## C. Files, previews, OS integration (GET)

`/file?path=` FBX/BVH bytes · `/timg?path=` `/cimg?path=` images ·
`/audiofile?path=` audio with HTTP Range · `/preview/<key>.webm`
animation preview (HEAD works for link checks) ·
`/api/open_explorer?path=&dry=1` resolve/show in Explorer (relative
paths resolve against the section roots).

## D. Search semantics (all item endpoints)

- Tokens: `a-z0-9` words, stemmed, 1-char tokens dropped. A query whose
  tokens are ALL dropped returns 0 (never the whole library).
- AND across tokens first; if nothing matches, automatic OR fallback —
  the response says so: `mode: "or-fallback"`, `exact: 0`, items
  `tier: 3`, ranked by token rarity (selective tokens first).
- `tier`: 1 = all tokens hit the name; 2 = AND via tags/themes/stems;
  3 = OR fallback. 0 = no query.
- Short tokens match on word boundaries (`lamp` ≠ `clamp`); tokens ≥5
  chars match as substrings.
- Percent-encode spaces: `?q=brick%20wall`. `size` clamps to 8–500 on
  every list endpoint (a floor of 8 always applies).

## E. POST endpoints (mutations — explicit instruction only)

`/api/collection/tag` add/remove a tag · `/api/collection/thumb` set
thumbnail · `/api/retag` bulk pack taxonomy · `/api/preview/store`
upload rendered preview · `/api/pack_source` set a pack's store URL.

## F. MCP alternative

Same registry via stdio MCP (`docs/MCP_SETUP.md`): `pharos_stats`,
`pharos_search_meshes`, `pharos_search_textures`, `pharos_search_audio`,
`pharos_search_collection`, `pharos_list_packs`. Note: MCP filters are
simpler than the HTTP stack — prefer HTTP for nuanced queries.
"""


def generate(db_path: str | None = None, repo_hint: str | None = None) -> list[Path]:
    """Write both agent docs into the configured agent_files folder."""
    db = db_path or config.DB_PATH
    c = _counts(db)
    repo = repo_hint or str(Path(__file__).resolve().parents[2])
    stamp = __import__("datetime").datetime.now().strftime("%Y-%m-%d %H:%M")
    target = config.AGENT_FILES
    target.mkdir(parents=True, exist_ok=True)

    start = START_TEMPLATE.format(
        library_root=config.LIBRARY_ROOT, generated=stamp, repo=repo, **c)
    api = API_TEMPLATE.replace("{generated}", stamp)

    paths = []
    for name, body in (("AGENT_START_HERE.md", start), ("AGENT_API.md", api)):
        p = target / name
        if p.is_file():                      # keep one generation of history
            p.replace(p.with_suffix(".md.bak-previous"))   # overwrites old bak
        p.write_text(body, encoding="utf-8")
        paths.append(p)
    return paths


def run_docs(argv=None) -> int:
    for p in generate():
        print(f"wrote {p}")
    return 0
