#!/usr/bin/env python3
"""
make_sandbox.py -- create the throwaway UE conversion sandbox locally.

The sandbox is NOT shipped in the repo on purpose: it is an empty UE
project whose whole job is to be a temporary workspace (pack Content is
robocopied INTO it, the headless engine run exports OUT of it, sources
stay read-only). It carries an EngineAssociation that must match the
machine's own UE install -- so it is generated here, on this machine,
from the UE_EXE you configured, instead of shipping a version-pinned
file that goes stale.

Creates (beside this script, or under --out):
    sandbox/Sandbox.uproject      empty project, PythonScriptPlugin enabled
    sandbox/Content/              where convert_packs.sh copies pack sources

Safe to delete and regenerate at any time; safe to re-run (refuses to
overwrite an existing sandbox unless --force).

Usage:
    python make_sandbox.py [--out DIR] [--engine-version X.Y] [--force]
    (UE_EXE env or --engine-version sets EngineAssociation; without
     either the field is omitted -- harmless for headless driver runs,
     which always invoke one specific UnrealEditor-Cmd binary.)
"""
import argparse
import json
import os
import re
import sys
from pathlib import Path

UPROJECT = {
    "FileVersion": 3,
    "Category": "",
    "Description": "Pharos conversion sandbox - throwaway empty project "
                   "generated by make_sandbox.py. Pack sources are copied "
                   "in temporarily and never modified in place. Safe to "
                   "delete and regenerate.",
    "Plugins": [
        {"Name": "PythonScriptPlugin", "Enabled": True},
    ],
}


def engine_version_from_ue_exe(ue_exe: str) -> str | None:
    """'.../UE_5.7/Engine/Binaries/Win64/UnrealEditor-Cmd.exe' -> '5.7'."""
    m = re.search(r"UE_(\d+\.\d+)", ue_exe or "")
    return m.group(1) if m else None


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default=None,
                    help="target dir (default: sandbox/ beside this script)")
    ap.add_argument("--engine-version", default=None, dest="engine_version",
                    help="EngineAssociation, e.g. 5.7 (default: derived "
                         "from UE_EXE; omitted when not derivable)")
    ap.add_argument("--force", action="store_true",
                    help="regenerate even if the sandbox already exists")
    args = ap.parse_args()

    target = (Path(args.out).resolve() if args.out else
              Path(__file__).resolve().parent / "sandbox")
    uproject = target / "Sandbox.uproject"

    if uproject.is_file() and not args.force:
        print(f"sandbox already exists: {uproject}")
        print("(delete it or pass --force to regenerate)")
        return 0

    version = args.engine_version or engine_version_from_ue_exe(
        os.environ.get("UE_EXE", ""))
    doc = dict(UPROJECT)
    if version:
        doc["EngineAssociation"] = version

    (target / "Content").mkdir(parents=True, exist_ok=True)
    uproject.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")

    print(f"sandbox created: {uproject}")
    assoc = doc.get("EngineAssociation") or \
        "(none - headless driver runs pass the binary explicitly)"
    print(f"  engine association: {assoc}")
    print("  plugin: PythonScriptPlugin (enabled)")
    print("next: re-run your convert_packs.sh / relink_pack.sh command")
    return 0


if __name__ == "__main__":
    sys.exit(main())
